### ISSUE TITLE
can't silence whatsapp beeps of incoming messages 

### ISSUE THREAD

**Issue by yuvalaviel** [olubunmitosin/whatsapp#1]
ubuntu 18.4, Gnome 3

**Comment by olubunmitosin** [comment]
Thanks for this feedback, we'll work on this and push an update release within the next 3days.

**Comment by olubunmitosin** [comment]
Hi, an update has been pushed v1.2.5. 
You now have two options;
- Toggle desktop and notification sounds by clicking on "2 vertical dots" to open settings on your whatsapp, then Notifications, and check your preferences. Or

- On the "Action" window menu, toggle it to Mute or Unmute the application sound completely.
NOTE: This will mute even audio messages and video sounds with notifications inclusively.

**Comment by yuvalaviel** [comment]
excellent - i'll try it.
