### ISSUE TITLE
File dialog only presents "Replacement Glyphs"

### ISSUE THREAD

**Issue by topotech** [olubunmitosin/whatsapp#23]
As the title said, for me (using a stable up-to-date Manjaro with Gnome shell) when Kesty Whatsapp opens a file dialog, all characters are rendered ad blank boxes: 

![imagen](https://user-images.githubusercontent.com/8272252/157325724-8384c1f1-16d7-492f-be67-a325a870acba.png)

My best guess is that there is a font missing or the encoding is trying to use characters outside the Latin character set, but I'm not sure why or how to fix it. This only happens with this application, which was installed through Snap.

**Comment by olubunmitosin** [comment]
Kindly update to version 1.2.7 and let me know if your issue is resolved.
Thanks.
