### ISSUE TITLE
update available prompt ...

### ISSUE THREAD

**Issue by shantiq** [olubunmitosin/whatsapp#31]
almost everyday when we open this amazing app it says New Update Available

My request here and surely i cannot be the only one wishing for this is for this to be automated on load-up
Simply ask us ONCE then we can open without this prompt which is a tad an annoyance as so frequent

Many thanx. Surely that is an easy modification

Thank u again for this wonderful tool

shan

**Comment by olubunmitosin** [comment]
This has been reviewed and improved.
Install version 1.2.7 for better experience.

Thanks.

**Comment by shantiq** [comment]
Thank you I have it installed through snap so not sure when it will be updated.   Again thanx for the program
